# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Runner' do

end

flutter_application_path = '../ios/'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)